# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('posicao', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('posicao', models.PositiveSmallIntegerField()),
                ('datatempo', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('datatempo', models.DateTimeField(verbose_name='date published')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriais.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='secao',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriais.Tutorial'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriais.Secao'),
        ),
    ]
