# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao',
            name='datatempo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='datatempo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='secao',
            unique_together=set([('id', 'tutorial')]),
        ),
    ]
