# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0002_auto_20161114_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
